FROM node:22.19-alpine3.22 AS builder

WORKDIR /certificate

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:1.29.1-alpine

COPY --from=builder /certificate/dist /var/www/localhost/html/certificate

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]
